services:
  backend:
    build: .
    container_name: bambochat-backend
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN}
      - BREVO_API_KEY=${BREVO_API_KEY}
      - BREVO_URL=${BREVO_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CLOUDINARY_NAME=${CLOUDINARY_NAME}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: "no"
